// Code generated by protoc-gen-go. DO NOT EDIT.
// source: core.proto

/*
Package packets is a generated protocol buffer package.

It is generated from these files:
	core.proto

It has these top-level messages:
	Packet
	Data
*/
package packets

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Packet struct {
	// Types that are valid to be assigned to Body:
	//	*Packet_Data
	Body isPacket_Body `protobuf_oneof:"body"`
}

func (m *Packet) Reset()                    { *m = Packet{} }
func (m *Packet) String() string            { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()               {}
func (*Packet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isPacket_Body interface {
	isPacket_Body()
}

type Packet_Data struct {
	Data *Data `protobuf:"bytes,1,opt,name=data,oneof"`
}

func (*Packet_Data) isPacket_Body() {}

func (m *Packet) GetBody() isPacket_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Packet) GetData() *Data {
	if x, ok := m.GetBody().(*Packet_Data); ok {
		return x.Data
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Packet) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Packet_OneofMarshaler, _Packet_OneofUnmarshaler, _Packet_OneofSizer, []interface{}{
		(*Packet_Data)(nil),
	}
}

func _Packet_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Packet)
	// body
	switch x := m.Body.(type) {
	case *Packet_Data:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Data); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Packet.Body has unexpected type %T", x)
	}
	return nil
}

func _Packet_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Packet)
	switch tag {
	case 1: // body.data
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Data)
		err := b.DecodeMessage(msg)
		m.Body = &Packet_Data{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Packet_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Packet)
	// body
	switch x := m.Body.(type) {
	case *Packet_Data:
		s := proto.Size(x.Data)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Data struct {
	SequenceID uint32 `protobuf:"varint,1,opt,name=sequenceID" json:"sequenceID,omitempty"`
	Content    []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *Data) Reset()                    { *m = Data{} }
func (m *Data) String() string            { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()               {}
func (*Data) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Data) GetSequenceID() uint32 {
	if m != nil {
		return m.SequenceID
	}
	return 0
}

func (m *Data) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func init() {
	proto.RegisterType((*Packet)(nil), "packets.Packet")
	proto.RegisterType((*Data)(nil), "packets.Data")
}

func init() { proto.RegisterFile("core.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 140 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0xce, 0x2f, 0x4a,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2f, 0x48, 0x4c, 0xce, 0x4e, 0x2d, 0x29, 0x56,
	0x32, 0xe5, 0x62, 0x0b, 0x00, 0x33, 0x85, 0x94, 0xb9, 0x58, 0x52, 0x12, 0x4b, 0x12, 0x25, 0x18,
	0x15, 0x18, 0x35, 0xb8, 0x8d, 0x78, 0xf5, 0xa0, 0x2a, 0xf4, 0x5c, 0x12, 0x4b, 0x12, 0x3d, 0x18,
	0x82, 0xc0, 0x92, 0x4e, 0x6c, 0x5c, 0x2c, 0x49, 0xf9, 0x29, 0x95, 0x4a, 0x0e, 0x5c, 0x2c, 0x20,
	0x71, 0x21, 0x39, 0x2e, 0xae, 0xe2, 0xd4, 0xc2, 0xd2, 0xd4, 0xbc, 0xe4, 0x54, 0x4f, 0x17, 0xb0,
	0x56, 0xde, 0x20, 0x24, 0x11, 0x21, 0x09, 0x2e, 0xf6, 0xe4, 0xfc, 0xbc, 0x92, 0xd4, 0xbc, 0x12,
	0x09, 0x26, 0x05, 0x46, 0x0d, 0x9e, 0x20, 0x18, 0x37, 0x89, 0x0d, 0xec, 0x10, 0x63, 0x40, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x3b, 0x3e, 0xa4, 0x93, 0x96, 0x00, 0x00, 0x00,
}
